name: auditmysite_cli
description: Build HTML reports from audit JSONs
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  shared:
    path: ../shared
  args: ^2.5.0
  path: ^1.9.0
  glob: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
