name: shared
description: Shared models and utils for auditmysite
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.8.0
  lints: ^3.0.0
